# Generated by Django 3.2 on 2023-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SecretsPassword',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='boolfield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='boolfield1',
            field=models.BooleanField(default=False),
        ),
    ]
