# Generated by Django 3.2 on 2023-02-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230223_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('markers | marker | Can change marker', 'markers | marker | Can view marker'), ('markers | rental | Can add rental', 'markers | rental | Can change rental '), ('markers | phone | Can change phone', 'markers | phone | Can view phone'), ('markers | phone | Can add phone', 'markers | phone | Can change phone'))},
        ),
    ]
