# Generated by Django 3.2 on 2023-02-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='latitude',
            new_name='Latitude',
        ),
    ]
