# Generated by Django 3.2 on 2023-02-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_rename_latitude_marker_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='geolocation',
        ),
    ]
