<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-02-17 14:35
=======
# Generated by Django 3.2 on 2023-02-21 15:48
>>>>>>> ac22261add13a8530970a5e840ac37867f9d8ae3

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ("markers", "0004_auto_20230217_1256"),
=======
        ('markers', '0004_auto_20230217_1256'),
>>>>>>> ac22261add13a8530970a5e840ac37867f9d8ae3
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50)),
                ("IMEMI", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
=======
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('IMEMI', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> ac22261add13a8530970a5e840ac37867f9d8ae3
            ],
        ),
    ]
