# Generated by Django 3.2 on 2023-02-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_rename_latitude_marker_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='network',
            field=models.CharField(max_length=50),
        ),
    ]
