# Generated by Django 3.2 on 2023-02-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_marker_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='continent_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_tld',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='postal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
