# Generated by Django 3.2 on 2023-02-22 22:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_auto_20230223_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='asn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_area',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_calling_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_capital',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_code_iso3',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='country_population',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='currency_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='marker',
            name='network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='org',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='region',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='region_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='timezone',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='utc_offset',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='version',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
