# Generated by Django 3.2 on 2023-02-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0008_alter_marker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
